import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const interFont = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "SkillSphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${interFont.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="container mx-auto">{children}</main>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
